### ISSUE TITLE
Jobs with phantomjs failing to ignore dupes

### ISSUE THREAD

**Issue by rwoodpecker** [ArchiveTeam/ArchiveBot#179]
This has been observed many times, example: 9tw6b0kfy2ne3026776lsoppc. Tumblr, twitter and other  jobs that utilise phantomjs appear to endlessly grab things over and over again. One job grabbed robots.txt on twitter literally thousands of times before it was aborted.

Not sure if this occurs every time phantomjs is utilised~~, but appears it might be so.~~

**Comment by JustAnotherArchivist** [comment]
I'm not sure about robots.txt, but the general duplication is a result of how wpull and phantomjs are linked, as far as I understand it. wpull executes phantomjs individually for each URL (with a proxy parameter so it can intercept the network traffic and write it to WARCs). phantomjs needs to have all page resources to work properly. But because a new phantomjs process is spawned for each URL, it cannot possibly have any resources from the previous loads and therefore has to redownload everything. I believe wpull also happily writes all these re-retrievals to the WARCs (though there is a `--warc-dedup` option that should avoid this).

I can think of several ways to avoid this and of various reasons why each of those is probably not going to work properly. A better long-term solution is likely to use a real browser in headless mode (Chromium's was released in the stable build recently, and Firefox's will likely land in version 56 in September) instead, which handles caching etc. That would also have various other advantages, e.g. archival of everything pretty much exactly how the average user would see it, more realistic traffic patterns, and proper cookie handling. I plan on looking into this once Firefox's headless mode is available.

**Comment by falconkirtaran** [comment]
PhantomJS is no longer maintained, and so the correct solution to this 
is to use headless Chromium or something like it.  There is a 
deduplication layer in the archivebot wpull hooks (if memory serves), 
but since page fetches are nearly always the bottleneck in a crawl it 
would be good to reduce the number.

I don't think tweaking our use of phantomjs is worthwhile since we 
already mean to replace it.

**Comment by JustAnotherArchivist** [comment]
> PhantomJS is no longer maintained, and so the correct solution to this is to use headless Chromium or something like it.

Yep, hence my second paragraph. :-)

**Comment by JustAnotherArchivist** [comment]
Obsoleted by #390
