### ISSUE TITLE
Add ETA to dashboard

### ISSUE THREAD

**Issue by picsi** [ArchiveTeam/ArchiveBot#232]
The new dashboard has a completion bar. It would be handy to have an ETA and perhaps a percentage too.

**Comment by yipdw** [comment]
Those aren't completion bars -- it's responses bucketed by HTTP response code (1xx, 2xx, 3xx, 4xx, 5xx, and the zero-code used to indicate things like network failures).

This is similar to #229 otherwise, which I've put on the "I don't think we'll get to this" because we don't really have the data to provide a useful estimate.
