### ISSUE TITLE
Replace !abort with !stop and !kill

### ISSUE THREAD

**Issue by yipdw** [ArchiveTeam/ArchiveBot#93]
When we switched to wpull in linked-pages mode, we started getting many more page requisites.  This is good, but sometimes the job goes too far and we _don't_ want to upload the result to IA.  However, `!abort` stops wpull and uploads whatever it got to a staging site.

There now seems to be a need for two ways to abort a job:

1. `!stop IDENT`: tell the job to stop and upload whatever it got
2. `!kill IDENT`: kill the job, erasing all local data and upload nothing

Under this plan, `!abort` will do something like this:

```
<me> !abort abc123
<ArchiveBot> me: !abort abc123 has been deprecated.
<ArchiveBot> me: Use !stop abc123 to stop the job and upload current crawl, !kill abc123 to remove job data and upload nothing.
```

We could also just keep `!abort` as-is, but I don't want three ways to stop a job.

**Comment by falconkirtaran** [comment]
Since the job is not entirely buffered on the pipeline but is sent upwards in 5gb chunks, kill would not perform as a naive user might expect.

**Comment by ethus3h** [comment]
My 2 cents: Given @falconkirtaran's comment above, a !kill option seems kind of silly since it would only be 5GB of extra responses stored (unless there was a really big response, which doesn't seem that common). 5GB seems kind of a negligible amount of data to store to be able to say there's a complete record. (I'm quite averse to the idea of deleting things without a very compelling reason.)

**Comment by yipdw** [comment]
Yeah, this issue was raised before incremental upload became a thing, which means that `!kill` can't fulfill its purpose.

Closing as won't do.
